language: python

cache: pip
sudo: false
python:
    - 3.4
    - 3.5
    - 3.6

before_install:
    - pip install -U pip
    - pip install -U pytest pytest-cov pytest-benchmark codecov

install:
    - pip install -U numpy scipy python-libsbml lxml
    - pip install -e .

script:
    - py.test --benchmark-skip --cov=corda

after_success:
    - codecov
