language: python

sudo: false
python:
    - 3.4
    - 3.5

install:
  - pip install cobra numpy scipy python-libsbml lxml codecov coverage
  - pip install .

script:
    - coverage run setup.py test
    - codecov
