language: python

sudo: false
python:
    - 3.4
    - 3.5

before_install:
    - pip install -U pip

install:
  - pip install -U cobra numpy scipy python-libsbml lxml codecov coverage
  - pip install .

script:
    - coverage run setup.py test
    - codecov
